---
# tasks file for common
- name: Set hostname
  hostname: name="{{ inventory_hostname }}"
- name: Set /etc/hosts
  template:
    src: "{{ role_path }}/templates/hosts.j2"
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    backup: yes
- name: Set authorized_keys for user ubuntu
  copy:
    src: "{{ role_path }}/files/authorized_keys"
    dest: /home/ubuntu/.ssh/authorized_keys
    owner: ubuntu
    group: ubuntu
    mode: 0600
    backup: yes
- name: Install pycurl
  apt: pkg={{ pkg_pycurl }} state=installed update_cache=true
- name: Install ntp
  apt: pkg={{ pkg_ntp }} state=installed update_cache=true
- name: Activate ntp
  service:
    name: ntp
    enabled: yes
    state: started
- name: Set interfaces file to load all interfaces in interfaces.d
  copy:
    src: "{{ role_path }}/files/interfaces"
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
    backup: yes
- name: Set internal network config
  template:
    src: "{{ role_path }}/templates/60-internal.cfg.j2"
    dest: /etc/network/interfaces.d/60-internal.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes
- name: Apply internal network config
  shell: "ifdown {{ iface_internal }} && ifup {{ iface_internal }}"
- name: Download Ambari repository list
  get_url:
    url: "{{ ambari_repo_list }}"
    dest: /etc/apt/sources.list.d/ambari.list
    mode: 0644
    backup: yes
- name: Add Ambari repository key
  apt_key:
    keyserver: "{{ ambari_repo_keyserver }}"
    id: "{{ ambari_repo_keyid }}"
- name: Update apt cache
  apt:
    update_cache: yes
- name: Copy transparent-huge-pages service file
  copy:
    src: disable-transparent-hugepages
    dest: "/etc/init.d/disable-transparent-hugepages"
    mode: 0755
- name: Run service to disable transparent hugepages
  service:
    name: disable-transparent-hugepages
    state: started
    enabled: yes


